version: 2.1
executors:
  arm:
    machine:
      image: ubuntu-2404:current
    resource_class: arm.medium

jobs:
  test-arm:
    executor: arm
    steps:
      - run: uname -a
      - run: go env
      - run: go build -o main
  test-arm1:
    executor: arm
    steps:
      - run: uname -a
      - run: sudo go env
      - run: go build -o main

workflows:
  ceems:
    jobs:
      - test-arm:
          filters:
            tags:
              only: /.*/
      
      - test-arm1:
          filters:
            tags:
              only: /.*/
