version: 2.1
executors:
  arm:
    machine:
      image: ubuntu-2404:current
    resource_class: arm.medium

jobs:
  test-arm:
    executor: arm
    steps:
      - checkout
      - run: uname -a
      - run: go env
      - run: go build -o main
  test-arm1:
    executor: arm
    steps:
      - checkout
      - run: uname -a
      - run: |
          GO_VERSION=1.25.2
          wget -O /tmp/go${GO_VERSION}.linux-arm64.tar.gz https://go.dev/dl/go${GO_VERSION}.linux-arm64.tar.gz
          sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf /tmp/go${GO_VERSION}.linux-arm64.tar.gz
      - run: go env
      - run: go build -o main

workflows:
  ceems:
    jobs:
      - test-arm:
          filters:
            tags:
              only: /.*/
      
      - test-arm1:
          filters:
            tags:
              only: /.*/
