version: 2.1
orbs:
  go: circleci/go@3.0.3
executors:
  arm:
    machine:
      image: ubuntu-2404:current
    resource_class: arm.medium

jobs:
  test-arm:
    executor: arm
    steps:
      - run: uname -a
      - run: go env
      - run: go build -o main
  test-arm1:
    executor: arm
    steps:
      - run: uname -a
      - run: sudo go env
      - run: go build -o main
  test-go-orb:
    executor:
      name: go/default
      tag: 1.25
      machine:
        image: ubuntu-2404:current
      resource_class: arm.medium
    steps:
      - run: uname -a
      - run: go env
      - run: go build -o main

workflows:
  ceems:
    jobs:
      - test-arm:
          filters:
            tags:
              only: /.*/
      
      - test-arm1:
          filters:
            tags:
              only: /.*/
      
      - test-go-orb:
          filters:
            tags:
              only: /.*/
