version: 2.1
executors:
  arm:
    machine:
      image: ubuntu-2404:current
    resource_class: arm.medium

jobs:
  test-arm:
    executor: arm
    steps:
      - run: go env
      - run: uname -a
      # Fix for https://github.com/golang/go/issues/75031#issuecomment-3195256688
      # - run: go env -w GOTOOLCHAIN=go1.25.0+auto
      - run: |
          git clone https://github.com/ceems-dev/ceems.git
          cd ceems
          GOARCH=1 make clang
          make
          CGO_APPS=1 make

workflows:
  version: 2
  ceems:
    jobs:
      - test-arm:
          filters:
            tags:
              only: /.*/
